sudo: required
branches:
  except:
    - template
env:
  global:
    - TRAVIS_USER_UID=$(id -u)

install:
  - sudo apt-get install sshfs
  - sudo .travis/install-alpine
  - sudo .travis/setup-alpine
script:
  - sudo .travis/buildrepo
