#!/bin/sh
# vim: set ts=4:
set -eu

. "$(dirname "$0")"/common.sh

APK_TOOLS_URI='https://mirror.fit.cvut.cz/alpine/v3.3/main/x86_64/apk-tools-static-2.6.10-r0.apk'
APK_TOOLS_SHA256='47ef4dc147e45e9a6eb334bb01d649cb733dbbb5cac9437ffdac3b526f3da68b'


echo '\n==> Downloading apk-tools-static'

cd /tmp
wget "$APK_TOOLS_URI"
echo "$APK_TOOLS_SHA256  $(basename "$APK_TOOLS_URI")" | sha256sum -c
tar -xzf $(basename "$APK_TOOLS_URI")


echo '\n==> Installing Alpine Linux'

mkdir -p "$ALPINE_ROOT"/etc/apk
cd "$ALPINE_ROOT"

cp -R "$CLONE_DIR"/.keys etc/apk/keys
cp "$CLONE_DIR"/.travis/repositories etc/apk/repositories
cp /etc/resolv.conf etc/resolv.conf

/tmp/sbin/apk.static \
	--root . --update-cache --initdb --no-progress \
	add alpine-base

mount -t proc none proc
mount --rbind /sys sys
mount --rbind /dev dev
