#!/bin/sh
# vim: set ts=4:
set -eu

. "$(dirname "$0")"/common.sh

echo '\n==> Setting up Alpine Linux'

cd "$CLONE_DIR"

cp .keys/*.pub "$ALPINE_ROOT"/etc/apk/keys/

mkdir -p "$ALPINE_ROOT$(pwd)"
mount --bind "$(pwd)" "$ALPINE_ROOT$(pwd)"

alpine_run <<-EOF
	apk add alpine-sdk lua-aports

	patch -d / -p 1 < $(pwd)/.travis/abuild-sign.patch

	adduser -u $TRAVIS_USER_UID -G wheel -G abuild -s /bin/sh -D $ALPINE_USER
	echo '%wheel ALL=(ALL) NOPASSWD: ALL' > /etc/sudoers.d/wheel

	mkdir -p /var/cache/distfiles
	chmod a+w /var/cache/distfiles

	sed -i 's/JOBS=[0-9]*/JOBS=$(nproc)/' /etc/abuild.conf
EOF
